version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Ecommerce-Products
      - PORT=8000
      - SKIP_SEED_ON_START=false
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
