apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fusion-electronics.backendName" . }}
  namespace: {{ include "fusion-electronics.namespace" . }}
  labels:
    {{- include "fusion-electronics.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fusion-electronics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "fusion-electronics.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "fusion-electronics.configName" . }}
            - secretRef:
                name: {{ include "fusion-electronics.secretName" . }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
