{{- if and .Values.observability.enabled .Values.observability.fluentBit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion-electronics.fluentBitName" . }}-elastic
  namespace: {{ include "fusion-electronics.observabilityNamespace" . }}
  labels:
    {{- include "fusion-electronics.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.observability.elasticsearch.username | quote }}
  password: {{ .Values.observability.elasticsearch.password | quote }}
{{- end }}
