{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion-electronics.frontendName" . }}
  namespace: {{ include "fusion-electronics.namespace" . }}
  labels:
    {{- include "fusion-electronics.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  podSelector:
    matchLabels:
      {{- include "fusion-electronics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceLabel | nindent 14 }}
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "fusion-electronics.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.containerPort }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion-electronics.backendName" . }}
  namespace: {{ include "fusion-electronics.namespace" . }}
  labels:
    {{- include "fusion-electronics.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "fusion-electronics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "fusion-electronics.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: frontend
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceLabel | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.containerPort }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
