apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion-electronics.secretName" . }}
  namespace: {{ include "fusion-electronics.namespace" . }}
  labels:
    {{- include "fusion-electronics.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: {{ include "fusion-electronics.mongoUri" . | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  PINECONE_API_KEY: {{ .Values.secrets.PINECONE_API_KEY | quote }}
  PINECONE_HOST: {{ .Values.secrets.PINECONE_HOST | quote }}
  PINECONE_INDEX: {{ .Values.secrets.PINECONE_INDEX | quote }}
  WEAVIATE_HOST: {{ .Values.secrets.WEAVIATE_HOST | quote }}
  WEAVIATE_API_KEY: {{ .Values.secrets.WEAVIATE_API_KEY | quote }}
