{{- if and .Values.observability.enabled .Values.observability.teamsAlert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion-electronics.teamsAlertName" . }}-secrets
  namespace: {{ include "fusion-electronics.observabilityNamespace" . }}
  labels:
    {{- include "fusion-electronics.labels" . | nindent 4 }}
type: Opaque
stringData:
  TEAMS_WEBHOOK_URL: {{ .Values.observability.teamsAlert.webhookUrl | quote }}
  ES_USER: {{ .Values.observability.elasticsearch.username | quote }}
  ES_PASSWORD: {{ .Values.observability.elasticsearch.password | quote }}
{{- end }}
