apiVersion: v2
name: fusion-electronics
description: Helm chart for the Fusion Electronics MERN e-commerce application
type: application
version: 0.2.0
appVersion: "1.1.1"
dependencies:
  - name: mongodb
    version: "18.6.34"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
